const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const MessageSchema = new Schema({
    title0: String,
    title: String,
    title1: String,
    title2: String,
    title3: String,
    title4: String,
    title5: String,
    title6: String,
    title7: String,
    title8: String,
    title9: String,
    title10: String,
    title11: String,
    title12: String,
    title13: String,
    title14: String,
    title15: String,
    title16: String,
    title17: String,
    title18: String,
    title19: String,
    title20: String,
    title21: String,
    title22: String,
    title23: String,
    title24: String,
    title25: String,
    title26: String,
    title27: String,
    title28: String,
    title29: String,
    title30: String,
    title31: String,
    title32: String,
    title33: String,
    news: String,
    news1: String,
    news2: String,
    news3: String,
    lol: String,
    lol1: String,
    lol2: String,
    lol3: String,
    technology: String,
    technology1: String,
    technology2: String,
    technology3: String,
    emigrant: String,
    emigrant1: String,
    emigrant2: String,
    emigrant3: String,
    fashion: String,
    fashion1: String,
    fashion2: String,
    fashion3: String,
    films: String,
    films1: String,
    films2: String,
    films3: String,
    music: String,
    music1: String,
    music2: String,
    music3: String,
    games: String,
    games1: String,
    games2: String,
    games3: String,
    linguistics: String,
    linguistics1: String,
    linguistics2: String,
    linguistics3: String,
    literature: String,
    literature1: String,
    literature2: String,
    literature3: String,
    medic: String,
    medic1: String,
    medic2: String,
    medic3: String,
    quote: String,
    quote1: String,
    quote2: String,
    quote3: String,
    pictures: String,
    pictures1: String,
    pictures2: String,
    pictures3: String,
    politic: String,
    politic1: String,
    politic2: String,
    politic3: String,
    sport: String,
    sport1: String,
    sport2: String,
    sport3: String,
    xxx: String,
    xxx1: String,
    xxx2: String,
    xxx3: String,
    start: String,
    help1: String,
    top10: String,
    one: String

});

const Message = mongoose.model('catalogs', MessageSchema);

module.exports = Message;